[package]
name = "adrenaline"
version = "0.0.0"

[dependencies]
ed25519-dalek = { version = "1.0.0-pre", features = ["serde"] }
serde = { version = "1.0.87" }
serde_cbor = { version = "0.9.0" }
serde_derive = { version = "1.0.87" }
uuid = { version = "0.7.2", features = ["serde"] }
