[package]
name = "adrenaline"
version = "0.0.0"

[dependencies]
bitflags = { version = "1.0.4" }
serde = { version = "1.0.87" }
serde_cbor = { version = "0.9.0" }
serde_derive = { version = "1.0.87" }
serde_json = { version = "1.0.38" }
uuid = { version = "0.7.2", features = ["serde"] }
